name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          version: 12
      - name: Github actions for yarn
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: install
      - name: Build React App
        run: yarn build
      - name: Install Surge
        run: npm install -g surge
      - name: Run surge
        run: surge ./build https://learn_react_boot2020.surge.sh/ --token ${{ secrets.SURGE_TOKEN }}
